app = "hoodx"
primary_region = "gru"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_000
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 2
memory = "1gb"
memory_mb = 2_048
