app = "hoodx"
primary_region = "gru"

[build]
  [build.args]
    NEXT_PUBLIC_SUPABASE_URL = "https://pcwekkqhcipvghvqvvtu.supabase.co"
    NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjd2Vra3FoY2lwdmdodnF2dnR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MDkwNTcsImV4cCI6MjA2Mzk4NTA1N30.s9atBox8lrUba0Cb5qnH_dHTVJQkvwupoS2L6VneXHA"
    NEXT_PUBLIC_APP_URL = "https://hoodx.ai"
    NEXT_PUBLIC_CACHE_BUST = "v2"
    NEXT_MATRIXX_AUTHORIZED_IDS = "7a3972f5-d603-4420-af55-4852ba61032e,de8aa205-318b-4890-8731-b2463185c885"

[env]
  NODE_ENV = "production"
  NEXT_PUBLIC_SUPABASE_URL = "https://pcwekkqhcipvghvqvvtu.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjd2Vra3FoY2lwdmdodnF2dnR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MDkwNTcsImV4cCI6MjA2Mzk4NTA1N30.s9atBox8lrUba0Cb5qnH_dHTVJQkvwupoS2L6VneXHA"
  NEXT_PUBLIC_CACHE_BUST = "v2"
  NEXT_MATRIXX_AUTHORIZED_IDS = "7a3972f5-d603-4420-af55-4852ba61032e,de8aa205-318b-4890-8731-b2463185c885"
  NEXT_FLY_APP_URL = "https://hoodx.fly.dev"
  NEXT_PUBLIC_APP_URL = "https://hoodx.ai"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjd2Vra3FoY2lwdmdodnF2dnR1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0ODQwOTA1NywiZXhwIjoyMDYzOTg1MDU3fQ.qokqoM6yHAZRj-iEpNR448fI3Br9Q57dYrF_g0LJHOo"
  
  # XGATE Global Payment Gateway
  XGATE_API_BASE_URL = "https://api.xgateglobal.com"
  XGATE_EMAIL = "xcleriston@gmail.com"
  XGATE_PASSWORD = "skPbp0tBhkrOLlg"
  XGATE_WEBHOOK_URL = "https://hoodx.ai/api/xgate-webhook"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 5
  processes = ["app"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
