app = "hoodx-websocket"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

# Serviço HTTP (health check, stats)
[[services]]
  internal_port = 3000
  protocol = "tcp"
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

# Serviço WebSocket
[[services]]
  internal_port = 8080
  protocol = "tcp"
  
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[services.ports]]
    port = 8080

  [[services.ports]]
    port = 8443
    handlers = ["tls"] 